# Generated by Django 4.2.6 on 2024-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0003_remove_cartitem_cart_remove_cartitem_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("men", "Men"), ("women", "Women"), ("kids", "Kids")],
                default="",
                max_length=30,
                verbose_name="product_gender",
            ),
        ),
    ]
