# Generated by Django 4.2.6 on 2024-05-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_product_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("pants", "Pants"), ("shirts", "Shirts")],
                default="",
                max_length=30,
                verbose_name="product_category",
            ),
        ),
    ]
