# Generated by Django 4.2.6 on 2024-05-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pants", "Pants"),
                    ("shirts", "Shirts"),
                    ("dress", "Dress"),
                    ("sweaters", "Sweaters"),
                    ("jackets", "Jackets"),
                    ("shoes", "Shoes"),
                    ("others", "Others"),
                ],
                default="",
                max_length=30,
                verbose_name="product_category",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                    ("xxl", "XXL"),
                ],
                default="",
                verbose_name="product_size",
            ),
        ),
    ]
