# Generated by Django 4.2.6 on 2024-05-19 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_product_seller"),
    ]

    operations = [
        migrations.CreateModel(
            name="InStoreProduct",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product.product",),
        ),
        migrations.CreateModel(
            name="ThriftProduct",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("product.product",),
        ),
    ]
