version: '3'
services:
    postgres:
        image: postgres:14.5
        restart: unless-stopped
        ports:
            - '5433:5432'
        environment:
            POSTGRES_PASSWORD: SuperSecret!23
        volumes:
            - .postgres-data/postgres:/var/lib/postgresql/data
        command: postgres -c stats_temp_directory=/tmp

    redis:
        image: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
        volumes:
            - .redis-data/redis:/data
        command: redis-server --save 20 1 --loglevel warning
