version: '3'
services:
    postgres:
        image: postgres:14.5
        restart: unless-stopped
        ports:
            - '5433:5432'
        environment:
            POSTGRES_PASSWORD: SuperSecret!23
        volumes:
            - .postgres-data/postgres:/var/lib/postgresql/data
        command: postgres -c stats_temp_directory=/tmp
