# Generated by Django 4.2.6 on 2024-05-12 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="role",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
