# Generated by Django 4.2.6 on 2024-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_role_user_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="user_avatar"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
