# Generated by Django 4.2.6 on 2024-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "user",
            "0004_user_avatar_user_mobile_no_alter_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="",
                max_length=30,
            ),
        ),
    ]
