# Generated by Django 4.2.6 on 2024-05-07 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("esewa", "ESewa"), ("card", "Card")],
                        default="esewa",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        default=0.0, verbose_name="order_amount"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("shipping", "Shipping"),
                            ("delivered", "Delivered"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
