# Generated by Django 4.2.6 on 2024-05-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_order_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(default="", verbose_name="delivery_date"),
        ),
    ]
