# Generated by Django 4.2.6 on 2024-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order_delivery_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("paid", "Paid"),
                    ("payment_pending", "Payment Pending"),
                    ("cancelled", "Cancelled"),
                    ("shipping", "Shipping"),
                    ("delivered", "Delivered"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
