# Generated by Django 4.2.6 on 2024-05-07 09:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForgotPasswordOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("otp_code", models.CharField(max_length=6)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created_at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires_at"
                    ),
                ),
            ],
        ),
    ]
